import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="mock-identitytoolkit" strategy="beforeInteractive">
          {`
            (function() {
              const okResponse = () => new Response(JSON.stringify({
                idToken: 'mock-token',
                localId: 'test-user',
                email: 'testuser@example.com'
              }), { status: 200, headers: { 'Content-Type': 'application/json' } });

              // Fetch interception
              const originalFetch = window.fetch;
              window.fetch = async (input, init) => {
                try {
                  const url = typeof input === 'string' ? input : input.url;
                  if (url && url.includes('identitytoolkit.googleapis.com')) {
                    return okResponse();
                  }
                } catch (e) {}
                return originalFetch(input, init);
              };

              // XMLHttpRequest interception
              const OriginalXHR = window.XMLHttpRequest;
              function MockXHR() {
                const xhr = new OriginalXHR();
                let intercepted = false;
                const originalOpen = xhr.open;
                xhr.open = function(method, url, async, user, password) {
                  if (typeof url === 'string' && url.includes('identitytoolkit.googleapis.com')) {
                    intercepted = true;
                    this.readyState = 4;
                    this.status = 200;
                    this.responseText = JSON.stringify({
                      idToken: 'mock-token',
                      localId: 'test-user',
                      email: 'testuser@example.com'
                    });
                    if (this.onreadystatechange) {
                      this.onreadystatechange();
                    }
                    return;
                  }
                  return originalOpen.call(this, method, url, async, user, password);
                };
                const originalSend = xhr.send;
                xhr.send = function(body) {
                  if (intercepted) {
                    // mimic async
                    setTimeout(() => {
                      if (this.onload) this.onload();
                      if (this.onloadend) this.onloadend();
                      if (this.onreadystatechange) this.onreadystatechange();
                    }, 0);
                    if (this.onload) this.onload();
                    if (this.onloadend) this.onloadend();
                    return;
                  }
                  return originalSend.call(this, body);
                };
                return xhr;
              }
              window.XMLHttpRequest = MockXHR;
            })();
          `}
        </Script>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
